name: Default

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Docker
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          image: yuyidev/stable-diffusion-webui
          addLatest: true
          directory: .
          dockerfile: ./Dockerfile
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}